# Generated by Django 6.0.4 on 2026-04-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorty',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
